avatar: https://cdn.jsdelivr.net/gh/zcmimi/cdn@master/img/avatar_2.webp
assets_rt: https://cdn.jsdelivr.net/gh/zcmimi/cdn@master/assets 
  # 如果有cdn提高assets文件夹的加载速度,请填入地址
  # 否则留空
theme: clean # (beauty|clean)

randomimg:
  type: folder # (folder|list)
  path: https://cdn.jsdelivr.net/gh/zcmimi/cdn@master/img
  cnt: 36
  suf: webp
  list: # urls

comment: 
  enable: True
  valine:
    enable: True
    appid: NLh0fhLRvD8gOWEC3vtOIRx5-gzGzoHsz 
    appkey: DSwqdjPFKAnO4CFMQypfkcB9
    placeholder: 说几句嘛qwq
  gitalk:
    enable: True
    clientID: 054902ee1548e6fe427e
    clientSecret: b31fac2b407311ca7e6673ab84727ae9562c69ba
    repo: zcmimi.github.io
    owner: zcmimi
    admin: zcmimi
    distractionFreeMode: 'false'

autopjax: False # auto pjax

music:
  enable: True
  server: netease
  id: 765727960
  order: random
  color: '#f7a4b9'

appbar:
  pages:
    标签云: /tags
    分类: /categories
    友链: /links
    工具集: /tools
    关于我: /about
    Traveling: https://travellings.now.sh/

head_card:
  enable: True
  img: https://cdn.jsdelivr.net/gh/zcmimi/cdn@master/img/1.webp
  logo: https://cdn.jsdelivr.net/gh/zcmimi/cdn@master/img/avatar_2.webp
  text: nya~
  introduction: oier & archlinuxer
  pages:
    标签云: /tags
    分类: /categories
    友链: /links
    工具集: /tools
    关于我: /about

footer:
  enable: True
  site_create_date: 2019
  site_till_date: 2020
  icons:
    github: https://github.com/zcmimi
    bilibili: https://space.bilibili.com/110897068
    zhihu: https://www.zhihu.com/people/zcmimi
    twitter: https://twitter.com/zc_mimi
  lastbuild: True

drawer:
  Pages:
  - content: 标签云
    url: /tags
    icon:
      typ: mdui # (mdui|mqii|img)
      data: bookmark_border
      color: black
  - content: 分类
    url: /categories
    icon:
      typ: mdui
      data: book
      color: black
  - content: 友链
    url: /links
    icon:
      typ: mdui
      data: link
      color: black
  - content: 工具集
    url: /tools
    icon:
      typ: mdui
      data: build
      color: black
  - content: 关于我
    url: /about
    icon:
      typ: mdui
      data: person
      color: black
  - content: 订阅
    url: /atom.xml
    icon:
      typ: mdui
      data: rss_feed
      color: black
  - content: 站点地图
    url: /sitemap.xml
    icon:
      typ: mdui
      data: list
      color: black
  - content: 评论管理
    url: https://nlh0fhlrsgij.leanapp.cn
    icon:
      typ: mdui
      data: comment
      color: black
  Catch me:
  - content: 给我写信
    url: http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=fwUcIBIWEhY-Dg5RHBAS
    icon:
      typ: mdui
      data: email
      color: dodgerblue
  - content: 电报
    url: https://t.me/zcmimi
    icon:
      typ: mqii
      data: telegram
      color: '#66ccff'
  - content: 推特
    url: https://twitter.com/zc_mimi
    icon:
      typ: mqii
      data: twitter
      color: rgba(29,161,242,1.00)
  - content: 哔哩哔哩
    url: https://space.bilibili.com/110897068
    icon:
      typ: mqii
      data: bilibili
      color: '#F06292'
  - content: 网易云音乐
    url: https://music.163.com/#/user/home?id=507163653
    icon:
      typ: mqii
      data: netease-cloud-music
      color: red
  - content: 知乎
    url: https://www.zhihu.com/people/zcmimi
    icon:
      typ: mqii
      data: zhihu
      color: '#0084ff'
  - content: 洛谷
    url: https://luogu.com.cn/user/36532
    icon_typ: img
    icon: https://www.luogu.com.cn/favicon.ico
  - content: Github
    url: https://github.com/zcmimi
    icon:
      typ: mqii
      data: github
      color: black
  Links:
  - content: Traveling
    url: https://travellings.now.sh/
    icon:
      typ: mqii
      data: telegram
      color: '#bbb'
search:
  typ: worker #(local|worker|algolia[todo]|)
  file: /pure_data.json
  api: https://blog_search.zcmimi.workers.dev

share_menu:
  twitter: True
  weibo: True
  qq: True

busuanzi: 
  enable: true

highlight:
  theme: github